[project]
name = "todos"
version = "1.0.0"
description = "A minimal todo application for the DIS 2025 course."
dependencies = [
    "flask (==3.1.1)",
    "psycopg2 (==2.9.10)",
    "SQLAlchemy(==2.0.41)",
    "flask-sqlalchemy (==3.0.4)",
]

[tool.setuptools]
py-modules = []
